const curricula = {
  'semester-1': [
    ['Weeks 1–2','Team operating system','Kickoff, role maps, Git simulation, shared glossary, feedback agreements.','Interview ethics, problem framing, observation notes.','Semantic HTML, CSS foundations, browser DevTools.','HTTP, Node/TypeScript foundations, request lifecycle.','Team charter + accessible static service page in a reviewed pull request.'],
    ['Weeks 3–4','Evidence into contracts','Turn a messy brief into stories, risks, acceptance criteria, and a release slice.','Synthesis, journeys, task flows, low-fidelity testing.','Responsive layout, progressive enhancement, form states.','REST conventions, API schemas, validation, error models.','Tested flow + agreed UI-state and OpenAPI contract.'],
    ['Weeks 5–6','First vertical slice','Plan and pair across track boundaries; hold design and code critiques.','Content design, accessible patterns, interactive prototype.','TypeScript, DOM behavior, accessibility tree, component thinking.','PostgreSQL modeling, migrations, query safety.','Service-access feature from prototype through persisted data.'],
    ['Weeks 7–8','Test what you assumed','Run sessions together; triage evidence and bugs without blame.','Usability protocol, WCAG 2.2 review, iteration rationale.','Vitest, browser testing, keyboard and screen-reader checks.','API integration tests, fixtures, logging and debugging.','Usability findings + accessible, tested feature release.'],
    ['Weeks 9–10','A shared system','Negotiate tokens, component APIs, data ownership, and contribution rules.','Design tokens, component anatomy, documentation.','React fundamentals, Storybook-style component states.','Auth concepts, sessions, authorization boundaries.','Versioned mini design system + authenticated profile slice.'],
    ['Weeks 11–12','Work in a live codebase','Issue refinement, branches, merge conflicts, PR review, feature flags.','Handoff annotations and design QA against the build.','Async UI, caching, loading/empty/error states.','Relational queries, pagination, concurrency, API evolution.','Community operations increment on a shared repository.'],
    ['Weeks 13–14','Change without breaking','Respond to a policy change; impact-map it before rebuilding.','Revise research assumptions, flows, content, and specs.','Refactor components; contract and regression tests.','Safe migration, backward compatibility, audit trail.','Group-booking change shipped without losing existing data.'],
    ['Week 15','Release and reflect','Release review, incident drill, demo for evidence, blameless retrospective.','Portfolio case-study evidence and decision audit.','Performance budget, production QA, technical narrative.','Deployment basics, monitoring signals, runbook.','Deployed increment + release notes + team/individual reflection.']
  ],
  'semester-2': [
    ['Weeks 1–2','Discover with a partner','Stakeholder kickoff, opportunity mapping, feasibility and ethics review.','Research plan, service blueprint, inclusive recruitment.','Prototype spikes, platform constraints, analytics plan.','Domain model spike, privacy/security risks, architecture options.','Evidence-backed capstone opportunity brief and risk register.'],
    ['Weeks 3–4','Shape the product','Set outcome measures, slice an MVP, estimate uncertainty, agree definition of done.','Test concepts, prioritize journeys, establish content model.','Application architecture, routing, server/client boundaries.','API/data contracts, threat model, deployment architecture.','Roadmap + tested prototype + architecture decision records.'],
    ['Weeks 5–6','Increment one: useful','Daily integration, contract tests, review rotation, stakeholder playback.','High-fidelity core journey and continuous design QA.','Accessible component implementation, form and server state.','AuthN/AuthZ, schema, service tests, seed data.','First usable production increment with baseline metrics.'],
    ['Weeks 7–8','Quality under pressure','Inject an outage and scope change; triage impact and communicate tradeoffs.','Failure journeys, recovery content, accessibility audit.','End-to-end tests, performance profiling, error recovery.','OWASP risks, rate limits, secrets, structured logs.','Incident report + hardened second release with changed scope.'],
    ['Weeks 9–10','Operate what you ship','Read production signals, interview users, prioritize with evidence.','Research-in-production, analytics ethics, iteration.','Core Web Vitals, telemetry, cross-browser reliability.','Observability, backups, jobs, caching and data retention.','Measured product improvement and operational dashboard.'],
    ['Weeks 11–12','Responsible acceleration','AI-use review: disclose prompts, verify output, protect data, preserve authorship.','AI-assisted synthesis critique; bias and consent review.','Review generated code for security, licenses, tests, maintainability.','Evaluate AI integrations, prompt injection and data boundaries.','AI usage log + verified improvement; rejected outputs documented.'],
    ['Weeks 13–14','Capstone release','Release candidate review, stakeholder acceptance, accessibility/security gates.','Final usability validation, content and design-system cleanup.','Regression suite, performance budget, deployment verification.','Migration/rollback rehearsal, monitoring and incident response.','Public capstone release with evidence against outcome measures.'],
    ['Week 15','Handover and lead','Onboard a new team using only the product’s documentation; final retro.','Research repository and design rationale handoff.','Architecture map, contribution guide, known debt.','Runbook, data dictionary, API docs, recovery test.','Partner handover + portfolio defense + 90-day learning plan.']
  ]
};

function render(panelId) {
  const panel = document.getElementById(panelId);
  panel.innerHTML = curricula[panelId].map((m, i) => `<details class="module" ${i === 0 ? 'open' : ''}><summary><span>${m[0]}</span><strong>${m[1]}</strong><i aria-hidden="true">+</i></summary><div class="module-content"><div><b>SHARED STUDIO</b><p>${m[2]}</p></div><div><b>UI/UX TRACK</b><p>${m[3]}</p></div><div><b>FRONT-END TRACK</b><p>${m[4]}</p></div><div><b>BACK-END TRACK</b><p>${m[5]}</p></div><div><b>INTEGRATED OUTPUT</b><p>${m[6]}</p></div></div></details>`).join('');
}
Object.keys(curricula).forEach(render);
const tabs = [...document.querySelectorAll('[role="tab"]')];
tabs.forEach((tab, index) => tab.addEventListener('click', () => {
  tabs.forEach((item, i) => { item.setAttribute('aria-selected', i === index); item.tabIndex = i === index ? 0 : -1; document.getElementById(item.getAttribute('aria-controls')).hidden = i !== index; });
}));
tabs.forEach((tab, index) => tab.addEventListener('keydown', (event) => { if (!['ArrowLeft','ArrowRight'].includes(event.key)) return; const next = (index + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; tabs[next].focus(); tabs[next].click(); }));
